# Simple utility helper for a Caddy server, mostly useful for TLS.
#
# In this file, we bring up a Caddy HTTP server. We like Caddy for
# the ease with which it gives us the ability to configure a TLS
# endpoint for our node, since it has a built-in Let's Encrypt tool.
---
services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - ./configs/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data/caddy_data:/data
      - ./data/caddy_config:/config
    environment:
      - CADDY_EMAIL=${CADDY_EMAIL:-example@domain.com}
    depends_on:
      - lightwalletd 
      - LIGHTWALLETD_DOMAIN=${LIGHTWALLETD_DOMAIN:-localhost}
    depends_on:
      - lightwalletd 
    networks:
      - zcash-network

networks:
  zcash-network:
    external: true
    name: zcash-network 
