version: '3.8'

services:
  init-zebra-env:
    image: zfnd/zebra:latest
    user: "root"
    entrypoint: [] # Overriding entrypoint to permit root operation.
    command: >
      sh -c "
        mkdir -p /var/cache/zebrad-cache/state/v26/mainnet &&
        chown -R 10001:10001 /var/cache/zebrad-cache
      "
    volumes:
      - zebra-data:/var/cache/zebrad-cache

  zebra:
    image: zfnd/zebra:latest
    restart: unless-stopped

    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    env_file:
      - .env
    volumes:
      - zebra-data:/var/cache/zebrad-cache
    configs:
      - source: zebra_config
        target: /etc/zebrad/zebrad.toml
        uid: '10001'
        gid: '10001'
        mode: 0440
    ports:
      - "8233:8233" # Mainnet Network (for peer connections)
      - "8232:8232" # Opens an RPC endpoint
    depends_on:
      init-zebra-env:
        condition: service_completed_successfully
    healthcheck:
      start_period: 2m
      interval: 30s
      timeout: 10s
      retries: 3
      test: ["CMD", "sh", "-c", "cat /proc/net/tcp | grep :2028 || exit 1"]


  init-zaino-perms:
    image: busybox:latest
    command: sh -c "mkdir -p /var/cache/zaino-cache && chown -R 2003:2003 /var/cache/zaino-cache"
    volumes:
      - zaino-data:/var/cache/zaino-cache
    user: "root"

  zaino:
    image: emersonian/zcash-zaino:0.1.2-zr4
    container_name: zaino
    command: ["--config", "/etc/zaino/zaino.toml"]
    ports:
      - "8137:8137" # GRPC port for lightwallet client connections.
    depends_on:
      init-zaino-perms:
        condition: service_completed_successfully
      zebra:
        condition: service_started
    volumes:
      - ./configs/zaino.toml:/etc/zaino/zaino.toml:ro
      - zaino-data:/var/cache/zaino-cache
    user: "2003:2003"
    restart: unless-stopped

configs:
  zebra_config:
    file: ./configs/zebrad.toml
  zaino_config:
    file: ./configs/zaino.toml

volumes:
  zebra-data:
    driver: local
  zaino-data:
    driver: local 
