version: "3.8"

services:
  zebra:
    image: emersonian/zcash-zebra:latest
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    env_file:
      - .env
    volumes:
      - ./data/zebrad-cache:/var/cache/zebrad-cache
    configs:
      - source: zebra_config
        target: /etc/zebrad/zebrad.toml
        uid: '2001'
        gid: '2001'
        mode: 0440
    ports:
      - "8233:8233" # Mainnet Network (for peer connections)
      - "8232:8232" # Opens an RPC endpoint
    healthcheck:
      start_period: 1m
      interval: 15s
      timeout: 10s
      retries: 3
      test: ["CMD-SHELL", "curl --data-binary '{\"id\":\"curltest\", \"method\": \"getinfo\"}' -H 'content-type: application/json' 127.0.0.1:8232 || exit 1"]

  lightwalletd:
    image: emersonian/zcash-lwd
    depends_on:
      zebra:
        condition: service_healthy
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    configs:
      - source: lwd_config
        target: /etc/lightwalletd/zcash.conf
        uid: '2002'
        gid: '2002'
        mode: 0440
    volumes:
      - lwd-cache:/var/lib/lightwalletd/db
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:9068/metrics >/dev/null 2>&1 || exit 1"]
      start_period: 20s
      interval: 30s
      timeout: 5s
      retries: 5
    command: >
      --no-tls-very-insecure
      --grpc-bind-addr=0.0.0.0:9067
      --http-bind-addr=0.0.0.0:9068
      --zcash-conf-path=/etc/lightwalletd/zcash.conf
      --data-dir=/var/lib/lightwalletd/db
      --log-file=/dev/stdout
      --log-level=7
      --donation-address=u14yr5fr2gzhedzrlmymtjp8jqsdryh6zpypnh8k2e2hq9z6jluz9hn9u088j02c3zphnf30he4pnm62ccyae6hfjjuqxlddhezw2te5p6xxhm68vvvpvynnzdcegq4c5u06slq673emarwjy5z0enj2ry53avx0nsmftpx4hhh5rhpgnc 
    ports:
      # For VPS proxy setup, use localhost-only binding to secure SSH tunnel
      # Uncomment the lines below and comment out the public ports for VPS setup
      # - "127.0.0.1:9067:9067"   # gRPC (localhost only for SSH tunnel)
      # - "127.0.0.1:9068:9068"   # HTTP metrics (localhost only)

      # For direct/public access (default)
      - "9067:9067" # gRPC
      - "9068:9068" # HTTP

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --cleanup --label-enable
    restart: unless-stopped

configs:
  zebra_config:
    file: ./configs/zebrad.toml
  lwd_config:
    file: ./configs/lightwalletd.conf

volumes:
  lwd-cache:
    driver: local
    driver_opts:
      type: none
      o: bind,create=true
      device: ${PWD}/data/lwd-cache
    name: lwd-cache

