{{- if .Values.zebra.enabled }}
{{- include "zcash-stack.pdb" (dict "replicas" .Values.zebra.replicas "name" .Values.zebra.name "minAvailable" .Values.zebra.pdb.minAvailable) }}
{{- end }}
{{- if .Values.zakura.enabled }}
---
{{ include "zcash-stack.pdb" (dict "replicas" .Values.zakura.replicas "name" .Values.zakura.name "minAvailable" .Values.zakura.pdb.minAvailable) }}
{{- end }}
{{- if .Values.lightwalletd.enabled }}
---
{{ include "zcash-stack.pdb" (dict "replicas" .Values.lightwalletd.replicas "name" .Values.lightwalletd.name "minAvailable" .Values.lightwalletd.pdb.minAvailable) }}
{{- end }}
{{- if .Values.zaino.enabled }}
---
{{ include "zcash-stack.pdb" (dict "replicas" .Values.zaino.replicas "name" .Values.zaino.name "minAvailable" .Values.zaino.pdb.minAvailable) }}
{{- end }}
{{- if .Values.dnsSeeder.enabled }}
---
{{ include "zcash-stack.pdb" (dict "replicas" .Values.dnsSeeder.replicas "name" .Values.dnsSeeder.name "minAvailable" .Values.dnsSeeder.pdb.minAvailable) }}
{{- end }}
{{- if .Values.zecd.enabled }}
---
{{ include "zcash-stack.pdb" (dict "replicas" .Values.zecd.replicas "name" .Values.zecd.name "minAvailable" .Values.zecd.pdb.minAvailable) }}
{{- end }}
