{{- if .Values.zaino.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.zaino.name }}-config
data:
  zainod.toml: |
    backend = "fetch"
    network = "{{ if eq (include "zcash-stack.testnet" $) "true" }}Testnet{{ else }}Mainnet{{ end }}"

    [grpc_settings]
    listen_address = "0.0.0.0:{{ .Values.zaino.service.port }}"

    [validator_settings]
    validator_jsonrpc_listen_address = "{{ .Values.zaino.rpcService }}:{{ if eq (include "zcash-stack.testnet" $) "true" }}18232{{ else }}8232{{ end }}"

    [service]
    timeout = {{ .Values.zaino.config.service.timeout }}
    channel_size = {{ .Values.zaino.config.service.channelSize }}

    [storage.cache]
    capacity = {{ .Values.zaino.config.cache.capacity }}
    shard_power = {{ .Values.zaino.config.cache.shardPower }}

    [storage.database]
    path = "/app/data"
    size = {{ .Values.zaino.config.dbSize }}
{{- end }}
