{{- if .Values.zaino.enabled }}
{{- include "zcash-stack.ingress" (dict
      "ctx" $
      "svc" .Values.zaino.ingress
      "name" (printf "%s-%s" .Release.Name .Values.zaino.name)
      "serviceName" .Values.zaino.name
      "servicePort" .Values.zaino.service.port) }}
{{- end }}
