{{- if .Values.zcashd.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.zcashd.name }}-config
data:
  zcashd.conf: |
    i-am-aware-zcashd-will-be-replaced-by-zebrad-and-zallet-in-2025=1
    txindex=1
    experimentalfeatures=1
    rpcuser={{ .Values.rpc.credentials.rpcUser }}
    rpcpassword={{ .Values.rpc.credentials.rpcPassword }}
    rpcbind=0.0.0.0
    rpcallowip=0.0.0.0/0
    {{- if .Values.zcashd.testnet }}
    testnet=1
    {{- end }}
    {{- if .Values.zcashd.lightwalletd }}
    lightwalletd=1
    {{- end }}
    {{- if .Values.zcashd.explorer }}
    insightexplorer=1
    {{- end }}
    {{- if .Values.zcashd.wallet }}
    {{- if .Values.zcashd.exportdir }}
    exportdir={{ .Values.zcashd.exportdir }}
    {{- end }}
    {{- else }}
    disablewallet=1
    {{- end }}
    {{- if .Values.zcashd.mine }}
    gen=1
    genproclimit={{ .Values.zcashd.genproclimit }}
    mineraddress={{ .Values.zcashd.mining_address }}
    equihashsolver=tromp
    minetolocalwallet=0
    {{- end }}
{{- end }}
